dist: xenial
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install -y autoconf autopoint libtool texinfo libssl-dev libbsd-dev
script:
  - ./autogen.sh && ./configure --enable-all-extensions && make
  - src/ed --version && make check
